name: Build and test plugin

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew build publishAllPublicationsToLocalRepository
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Run demo project
        working-directory: demo-project
        run: ./run.sh
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

