name: Build and test plugin

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle Wrapper
        run: ./gradlew build publishAllPublicationsToLocalRepository
        env:
          DEVELOCITY_ACCESS_KEY: ${{ secrets.DV_ACCESS_KEY }}

      - name: Run demo project
        working-directory: demo-project
        run: |
          ./gradlew -I demo.init.gradle.kts \
          -Ddevelocity.url=https://ge.solutions-team.gradle.com/ \
          -Ddevelocity.injection-enabled=true \
          -Ddevelocity.plugin.version=3.17.2

